name: safe_steps_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  dio: ^5.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  widget_to_marker: ^1.0.6
  firebase_core: ^3.15.2
  firebase_auth: ^5.6.2
  google_sign_in: ^6.2.2
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.5.2
  shared_preferences: ^2.3.4
  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^6.0.0
  socket_io_client: ^3.1.3
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
